- name: Setup Prompt
  ansible.builtin.shell: set-prompt gitlab-runner


- name: Create github directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: grunner
    group: grunner