name: Provision Tools Infra
on: [push, workflow_dispatch]
jobs:
  Provision:
    runs-on: ubuntu-latest #self-hosted
    steps:
      - uses: actions/checkout@v4 #get the code
      - run: terraform init