name: Provision vault setUp &date
on: [workflow_dispatch]
jobs:
  Provision:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4 #get the code
      - name: Run Vault setup
        run: ansible-playbook -i vault-internal.mdevops24.online, tool-setup.yml -e ansible_user=${{ secrets.SSH_USER }} -e ansible_password=${{ secrets.SSH_PASS }} -e tool_name=vault